### ISSUE TITLE
Issue when running CLI 

### ISSUE THREAD

**Issue by nimishbhuta** [JanuszNowak/janono.ado.testcase.associate.cli#18]
1) We have created a small test which looks like this

using janono.ado.testcase.associate;

namespace LFAutomation;

[TestFixture]
[janono.ado.testcase.associate.Organization("QET")]
public class TestCase1
{
    [Test]
    [janono.ado.testcase.associate.TestCase(185)]
    public void Test1()
    {
        Assert.Pass();
    }
}

Note : We have used [TestFixture] instead of [TestClass] as it was not working and also [TestMethod] was not working so we used [Test]
We have created the build successfully and the test also run successfully. 

2) After that we download the lasted version of CLI for windows 64 and then ran the command as mentioned but got an error.Pls see the screeshot

![image](https://github.com/JanuszNowak/janono.ado.testcase.associate.cli/assets/61412287/bbcb2946-9820-4671-8ec2-ead2420903ed)

**Comment by JanuszNowak** [comment]
@nimishbhuta hi it looks like runtime .net 7.0 is missing or project suppose to be compiled to .net 6.0.
In mean time I added new cli version https://github.com/JanuszNowak/janono.ado.testcase.associate.cli/releases/tag/0.4.1 working also with .net 8.0

**Comment by nimishbhuta** [comment]
@JanuszNowak  Thanks this issue is resolved once I downloaded  the current CLI as you mentioned and installed .net 8.0 runtime.
But faced with another issue where it does not map the test method with the test case. I will open a new issue.
